### ISSUE TITLE
Credentials visible

### ISSUE THREAD

**Issue by MarkObie** [exislow/kleinanzeigen-magic#1]
Great port, thanks a lot!
It might make sense to get rid of the API credentials or at least to obfuscate them heavily. Since the API is not public Ebay maybe change the creds once they find out.

Cheers

**Comment by exislow** [comment]
This is right. Maybe I will base encode them or something in the next commit, thanks!

But those credentials are present in each Android app of Kleinanzeigen. If eBay will change them one day, everybody needs to have an app update immediatly. I guess, this is not likely to happen.
