### ISSUE TITLE
How to Fix Verbose Message?

### ISSUE THREAD

**Issue by johann929292** [exislow/kleinanzeigen-magic#14]
Hello, im getting more and more verbose messages on my end and saw that you were able to fix it on your software? Im trying to write a little tool for my self as a hobby project. Could you guys give me a hint how to fix the verbose Messages on the User Authentification?

Thanks a lot!

**Comment by exislow** [comment]
Currently I do not know what you mean. Can you provide a specific example. Maybe also as a screenshot?

**Comment by exislow** [comment]
Closed due to inactivity.
