### ISSUE TITLE
The overview shows only 20 ads

### ISSUE THREAD

**Issue by towarisch** [exislow/kleinanzeigen-magic#16]
Hello,

first : very great tool. Makes my life easier! Ist it possible, that the tools shows more than 20 ads ? Currently there is no paging and only first 20 ads are shown. I have like 26 ads atm.

Thank you!

**Comment by exislow** [comment]
Thank you very much for reporting this. Have not tried it with so many ads, yet. I will try to confirm and fix it next week.

**Comment by exislow** [comment]
Fixed with `v0.6.5` (https://github.com/exislow/kleinanzeigen-magic/releases/tag/v0.6.5)
