### ISSUE TITLE
HTTP-Error 500 brings app to stuck

### ISSUE THREAD

**Issue by dojo90** [exislow/kleinanzeigen-magic#17]
When I was trying to refresh an ad, I got a "HTTP 500 ErrorCode". The loading spinner is still running, but nothing happens anymore..

![grafik](https://user-images.githubusercontent.com/17551597/150973693-5e136714-6b7a-4ce6-aaa2-875ca9fa6c55.png)

**Comment by exislow** [comment]
Thank you reporting this issue. I can confirm it. Will try to fix it in the next couple of days. Probably more changes to the Kleinanzeigen backend from the new Dutch owner...

**Comment by exislow** [comment]
I was just about to debug this issue but suddenly there is no issue anymore. I am able to push ads to the top of the seaerch result list again using kleinanzeigen-magic `v0.6.4`. Can you confirm this?

**Comment by dojo90** [comment]
After restarting the software, I was also able to renew all ads again. I think this was a one-off error on Kleinanzeigen's part.

**Comment by exislow** [comment]
Thanks for verification. Issue closed. Feel free to re-open this issue if these problems re-occure.
