### ISSUE TITLE
Login and Password not saved in MacOS version.

### ISSUE THREAD

**Issue by nsotnikov** [exislow/kleinanzeigen-magic#18]
Just a short question.
I noticed, that I must enter login and password on every program start.
Is this a bug regarding saving credentials just not implemented?

**Comment by exislow** [comment]
In general this feature is / was not on the list, thus this functionality never existed. But I can put it on the roadmap.

**Comment by nsotnikov** [comment]
@exislow this would be nice.
I will close the tickets.
