### ISSUE TITLE
Register with the API

### ISSUE THREAD

**Issue by YazzyTales** [exislow/kleinanzeigen-magic#20]
Nothing

**Comment by exislow** [comment]
I have not tried to use the bare metal api to register a user. I cannot help right now. But I suggest to reverse engineer the *.apk.

**Comment by YazzyTales** [comment]
I already did it and thats how its working. I might miss read it..If anyone could help. Maybe I do send wrong Content-Type or something else.

**Comment by exislow** [comment]
Author changed removed description.
