### ISSUE TITLE
Commercial ads are not copied correctly

### ISSUE THREAD

**Issue by JT1301** [exislow/kleinanzeigen-magic#21]
When creating a commercial ad in a private account, there is a button to make the ad "commercial". This opens an additional field where the imprint can be entered.

If such an ad is copied, both settings are lost.

![grafik](https://user-images.githubusercontent.com/10863564/155527176-8ca884ca-9c67-4792-b480-886612bae3e4.png)

**Comment by exislow** [comment]
Apologies for coming back to you that late and thank you for reporting this issue. I have fixed it. With the next release later that day all missing information of commercial ads will be copied correctly.
