### ISSUE TITLE
Rename Ad

### ISSUE THREAD

**Issue by alafad** [exislow/kleinanzeigen-magic#23]
Hello and thanks for your work, can you please add, that the Programm rename the deleted ad to "neu inseriert " or something else?

Greetings

**Comment by exislow** [comment]
I will ad an option to alter the ad name with the next release of this software.

**Comment by exislow** [comment]
Implemented in release `v0.7.0`. Get it here https://github.com/exislow/kleinanzeigen-magic/releases/tag/v0.7.0
