### ISSUE TITLE
Bug: Quote in Title during offering recreation (push up button) is shown as &quot;

### ISSUE THREAD

**Issue by Falcosc** [exislow/kleinanzeigen-magic#24]
If you push the ad up, it will recreate the offering totally fine (great job!)
But " is not handled correctly and does not get unescaped during ad creation.

1. Kleinanzeigen web page: Create an ad with Title: `This is a "Test"`
2. Kleinanzeigen-Magic: Hit push to top on `This is a "Test"`

Expected title: `This is a "Test"`
Actual title: `This is a &quot;Test&quot;`

**Comment by exislow** [comment]
Thanks for the report. I can confirm this bug. It also happens while using `/` and other special characters which need to be encoded if put into an XML structure. The Kleinanzeigen API works using XML syntax, this is why encoding is important here. But honestly I was not able to figure out so far how to fix this behavior.

I am open for any suggestions.

**Comment by Falcosc** [comment]
Sounds strange, I thought about accidentally double escaping.

Probably not worth investigating this minor this, but if you like the challenge, here are some more ways to escape characters:

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/46637835#46637835

**Comment by Falcosc** [comment]
If it is a tag value instead of a attribute value then " doesn't need escaping at all https://www.liquid-technologies.com/XML/EscapingData.aspx

**Comment by exislow** [comment]
Fixed with release `v0.7.0`. Get it here https://github.com/exislow/kleinanzeigen-magic/releases/tag/v0.7.0
