### ISSUE TITLE
Feature Request: Support for shipping price

### ISSUE THREAD

**Issue by Falcosc** [exislow/kleinanzeigen-magic#25]
One of the latest kleinanzeigen feature is the support of shipping cost.

Would be nice if these new fields could be added to the "push ad up" feature.

If you use the new shipping fields, they look like this

**Edit view:**
![Screenshot 2022-04-18 215620](https://user-images.githubusercontent.com/8665625/163870058-7afc7899-81ed-4583-ba81-4c2b2b31e605.jpg)

**Public view:**
![Screenshot 2022-04-18 215700](https://user-images.githubusercontent.com/8665625/163870090-7f90ba5d-655f-4456-96a5-bb5c0a386947.jpg)

**Comment by exislow** [comment]
What exactly do you mean? Would you like to alter the shipping costs while pressing "push ad up" the same way you currently can modify the ad price?

**Comment by Falcosc** [comment]
Just keeping the old price would be enough. The old version did lose the shipping option (was not a big deal, I just added it again)

**Comment by exislow** [comment]
I was not aware of this. I will try to fix it! Thanks for the report.

**Comment by Falcosc** [comment]
This is a new feature, I saw it last week the first time. Technically not a bug ;)

**Comment by exislow** [comment]
Fixed with release `v0.7.0`. Get it here https://github.com/exislow/kleinanzeigen-magic/releases/tag/v0.7.0
