### ISSUE TITLE
File access error

### ISSUE THREAD

**Issue by gsorick** [exislow/kleinanzeigen-magic#26]
Hi

at the moment im getting following error
_Unhandled Error
Error: ENOENT: no such file or directory, open 'C:/Users/user/AppData/Local/Temp/ebk-dvT879/50_50fe8747-f785-4f41-aa40-675e0792b252?rule=$_57.JPG'_
I thought its a permission problem in Windows. After restart and reinstall I still get this error where folder name "ebk-dvT879" every time changes.
Additionaly when I download your exe file windows finds a trojaner in your application named "uwamson.a ml". Or is this a false positive?

Regards

**Comment by exislow** [comment]
Thank you for the report. I have seen this already at a friends laptop and will try to fix it soon.

**Comment by exislow** [comment]
I cannot re-produce this bug. Can you tell me, if this occurs with every ad you would like to top up or only with certain ads? Some links to the affected ads would be great.

**Comment by babahayat** [comment]
Hello,

I have the same problem. I think it affects at least everyone who uses Windows or Windows 11. I can not re-release any display since then. I will be happy to help you solve the problem.

**Comment by exislow** [comment]
Fixed with release `v0.7.0`. Get it here https://github.com/exislow/kleinanzeigen-magic/releases/tag/v0.7.0
