### ISSUE TITLE
Disapearing Anzeigen

### ISSUE THREAD

**Issue by lhoff94** [exislow/kleinanzeigen-magic#28]
I upgraded to the current version (because the old one wasn't working any more) v0.7.0 and used the Application as i did before. 

For the first three ads the push up worked. Then for i guess 5 or 6 i deleted the old one and didn't create a new one. Only after i changed the price on one ad, i got an error message. 

I suggest to add a fail-safe mechanism that at least keeps the content of the deleted ads accessable i case something went wrong.

**Comment by exislow** [comment]
Thank you for this report. I have not experienced this so far and the code for the ad "top up" has not changed. It still only removes the old ad, if the creation of the new ad was successfull (see https://github.com/exislow/kleinanzeigen-magic/blob/master/src-electron/main-process/kleinanzeigen-workflow.js#L151). Thus, it still should be fail safe.

Can you paste me some links of your formerly disappearing ads, in case you are able to re-produce this.

**Comment by lhoff94** [comment]
Alright, i think i found the underlying issue. 
I just wanted to reupload the ad and got an error message stating that only 50 ads per month are free. 

![Screenshot_20220516-235656](https://user-images.githubusercontent.com/17600225/168689056-e3123905-3e16-42a7-ab2f-13a26effeb01.png)

**Comment by gsorick** [comment]
Hi

I had this issue today. After reup my ads i got every time a success message. But anyway all my adds disappeared!

Regards

**Comment by exislow** [comment]
@lhoff94 thank oyu for investigating. So the workflow is to create first the new ad and then delete the old ad, if the creation was successful. But I think, if you have already 50, a 51. ad can be successfully created but aparently is not getting assigned to your account. This is probably why this happens.

I will try to implement a check, which does not allow you to top-up ads, if you have fifty ads created in the last 30 days.

@gsorick how many ads do you have in your account?

**Comment by exislow** [comment]
The check was implemented and merged and is available with the next release of this app. Check the release page: https://github.com/exislow/kleinanzeigen-magic/releases
