### ISSUE TITLE
v0.7: This application cannot be executed on this PC

### ISSUE THREAD

**Issue by backupandforkacc** [exislow/kleinanzeigen-magic#31]
I get an error message when starting the current .exe file:

![grafik](https://user-images.githubusercontent.com/1709199/185670621-71629186-da65-4dbe-bf7f-47a3b18eb0a0.png)

I am using windows 10 on a mac.

**Comment by exislow** [comment]
Thank you for reporting this issue. Why do you use Windows 10 on a Mac? What kind of Mac do you have (Intel or Apple Silicon)? What virtualization software do you use?

You could simply download the macOS package and install it, see https://github.com/exislow/kleinanzeigen-magic/releases

**Comment by backupandforkacc** [comment]
I use a generic Windows System on a Mac with Intel Chip. So no Virtualization. I used an older version of your software and then installed the newest and now it works. Sorry for the trouble.

**Comment by exislow** [comment]
No worries. But you can simply use the `*.dmg` file, which is the mac version of this app.

**Comment by backupandforkacc** [comment]
Thanks, but I have overwritten the Mac System, so just Linux and Windows. But as is works now, I am fine.
