### ISSUE TITLE
Publish ads using command line.

### ISSUE THREAD

**Issue by alafad** [exislow/kleinanzeigen-magic#37]
Hello Exislow, 

could be it possible to publish ads via command line, I want to specify crontab or something else.

Thank you, for telling your work with us!

**Comment by exislow** [comment]
This is definately possible. But some major refactoring to https://github.com/exislow/kleinanzeigen-magic/blob/master/src-electron/main-process/kleinanzeigen-workflow.js is necessary. I will put this on future planning but cannot right now tell when I will find some time to implement this.

If this is urgent you could try to try / adapt https://github.com/tejado/ebk-client

**Comment by alafad** [comment]
Thanks for your quick answer, a implementation of this would be great.

I will have a look for the other repo.

**Comment by dojo90** [comment]
Additional arguments could add even more value to the whole thing:

## functions

- `renew [a|s|o] p` **renew ads**
- `delete [a|s|o] p` **delete ads**
- `adjust [a|s|o]` **adjust price**

## arguments

- `a | all` all ads
- `s | specific` renew a specific ad that equals parameter
- `o | older than` renew all ads older than parameter
- `p | optional parameter` can be a `timespan`, a `title` of an ad or price adjustment

The time parameter can be very useful to avoid hitting the 50 ads limit in 30 days https://github.com/exislow/kleinanzeigen-magic/issues/28#issuecomment-1128177694

**Comment by exislow** [comment]
This project is definitely more suitable for your request: https://github.com/tejado/ebk-client
