### ISSUE TITLE
Feature Request: Post EBK to Ebay, too

### ISSUE THREAD

**Issue by cukabeka** [exislow/kleinanzeigen-magic#39]
Often, I want to simultaneously offer something both at EBK and Ebay, in that case it would be great if there was a possibility to not only do the magic, but also prepare a ebay.de offer from the existing data.

**Comment by exislow** [comment]
eBay Kleinanzeigen (which will soon not have eBay in the name anymore, since it was sold to a Dutch company) and eBay are two total separate things. Unfortunately I do not have time to also reverse the eBay API. If anybody is willing to do so, feel free.
